In [16]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
items = ('TV,냉장고,전자레인지,컴퓨터,선풍기,믹서,믹서').split(",")
print(items) 
print(type(items))

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']
<class 'list'>


In [17]:
encoder.fit(items) # 중복을 제거하고 0,1,2,3,4 순서 번호를 갖게함
print(encoder.classes_)

['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [18]:
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 2, 2])

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

# fit + transforme 동시에, 절대 테스트 자료는 안됌
encoder.fit_transform(items)

array([0, 1, 4, 5, 3, 2, 2], dtype=int64)

In [ ]:
# LabelEncoder p117

# 문자로된 y값을 숫자로 변형해야할 때 필수
# fit은 값은 유니크하게 바뀌면서 0,1,2,3.. 할당
# transform은 fit된 값을 y에 적용

# train하고 test 나누기전 처음부터 숫자를 변경한 뒤, train / test 나누는 것을 권장
# 만약 나눠어져 있는 자료라면 train에만 fit,transform하고 test에는 transform만

In [ ]:
# yes , no
# LabelEncoding 으로

In [ ]:
# 문자 -> 숫자로변환 '원핫인코딩'
# x값은 0,1 이외에 2개 이상의 카테고리 변수는 원핫인코딩(pandas의 더미 변수)

In [20]:
# 원핫 인코딩 != 더미

# 2차원 이여야함
from sklearn.preprocessing import OneHotEncoder

items = ('TV,냉장고,전자레인지,컴퓨터,선풍기,믹서,믹서').split(",")
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

ValueError: Expected 2D array, got 1D array instead:
array=['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '믹서' '믹서'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np


items = ('TV,냉장고,전자레인지,컴퓨터,선풍기,믹서,믹서').split(",")
items = np.array(items).reshape(-1,1)
print(items.shape)

oh_encoder = OneHotEncoder()
oh_encoder.fit(items)

(7, 1)


OneHotEncoder()

In [6]:
oh_encoder.categories_

[array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')]

In [7]:
oh_labels = oh_encoder.transform(items)
# sparse matrix : 0이 많은 행렬(희소행렬)
# 특히 텍스트분석일 때

In [8]:
oh_labels

<7x6 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [9]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [10]:
oh_labels.shape

(7, 6)

In [11]:
classData = ('TV,냉장고,전자레인지,컴퓨터,선풍기,믹서,믹서').split(",")
maxindex = np.argmax(oh_labels.toarray(),axis=-1) # 행단위로 가장 큰 값 찾기
maxindex

array([0, 1, 4, 5, 3, 2, 2], dtype=int64)

In [12]:
for x in maxindex:
    print(classData[x])

TV
냉장고
선풍기
믹서
컴퓨터
전자레인지
전자레인지


In [43]:
# 너무 많은 category가 생긴다면 dummy 변수가 안좋을 수도 있다

In [44]:
# 문자 -> 숫자 '더미 변수'화 p119
# pandas의 기능임
# 카테고리에 해당하는 문자 변수를 낱개의 필드(x값)으로 쪼갬
# 문제점 : 단, 변수가 너무 많으면 x변수로 다 처리가 안됌 (일정량이상 되면 안됌)
# 해결방법 : 라쏘 모듈 사용 (L1 정규화)

In [46]:
# 스케일링
# 1) 표준화 (Standard) - StandardScaler
# 편차 : 평균과의 차이를 가지고 계산
# 데이터가 많을 수록 이상치는 큰 영향이 없어짐
# 2) 정규화 (Normlize) - MinMaxScaler
# x-min / max-min
# test는 fit 하지 않고 transform만함