In [6]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

##########데이터 로드

x_data = np.array([
    [2, 1],
    [3, 2],
    [3, 4],
    [5, 5],
    [7, 5],
    [2, 5],
    [8, 9],
    [9, 10],
    [6, 12],
    [9, 2],
    [6, 10],
    [2, 4]
])
y_data = np.array([0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

labels = ['fail', 'pass']

##########데이터 분석

##########데이터 전처리

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=777)

##########모델 생성

model = LogisticRegression(penalty='none')

##########모델 학습

model.fit(x_train, y_train)

##########모델 검증

##########모델 예측

x_test = np.array([
    [4, 6]
])

y_predict = model.predict(x_test)
y_predict

c:\Users\user\miniconda3\envs\py\Lib\site-packages\sklearn\linear_model\_logistic.py:1173: FutureWarning: `penalty='none'`has been deprecated in 1.2 and will be removed in 1.4. To keep the past behaviour, set `penalty=None`.
  warnings.warn(


array([0])

In [5]:
print(y_predict) #[1]
print(y_predict[0]) #1

[[0.84430359 0.15569641]]
[0.84430359 0.15569641]


In [7]:
label = labels[y_predict[0]]
y_predict = model.predict_proba(x_test)
y_predict

array([[0.84430359, 0.15569641]])

In [8]:
confidence = y_predict[0][y_predict[0].argmax()]
print(label, confidence) #

fail 0.8443035908681575


In [9]:
x_test = [
    [4, 6], 
    [10, 11]
]

y_predict = model.predict(x_test)
print(y_predict) #[1 1]
print(y_predict[0]) #1

[0 1]
0


In [10]:
label = labels[y_predict[0]]
label

'fail'

In [16]:
y_predict = model.predict_proba(x_test)
confidence = y_predict[0][y_predict[0].argmax()]
print(label, confidence) #
print(y_predict) #1

fail 0.8443035908681575
[[0.84430359 0.15569641]]


In [17]:
label = labels[y_predict]
y_predict = model.predict_proba(x_test)
confidence = y_predict[1][y_predict[1].argmax()]
print(label, confidence) #

IndexError: index 1 is out of bounds for axis 0 with size 1