In [ ]:
pip install scikit-learn

In [1]:
import sklearn

sklearn.__version__

'1.2.2'

In [49]:
pip show scikit-learn

Name: scikit-learn
Version: 1.2.2
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: c:\Users\user\miniconda3\envs\py\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [2]:
from sklearn.datasets import load_iris # 다항 분류에 대표적인 데이터
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd

iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [8]:
iris_df = pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
iris_df['label'] = iris_label
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(iris_data,iris_label,test_size=0.2,random_state=11)

In [11]:
dt_clf = DecisionTreeClassifier(random_state=11)

In [12]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [13]:
pred = dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred), accuracy_score(pred,y_test)

(0.9333333333333333, 0.9333333333333333)

In [ ]:
# 교차 검증 (Cross Validation)
# 정형데이터의 증강 기법

# K 폴드 교차 검증: 교차검증의 한 방법론
# 일반적으로 5 or 10 폴드 많이 씀

# GridSearchCV
# 교차 검증, 하이퍼 파라미터 튜닝을 한번에

In [16]:
import pandas as pd
from sklearn.linear_model import LinearRegression # wx + b 공식을 제공하는 에스티메이터
import numpy as np

##########데이터 로드

train_df = pd.read_excel('https://github.com/cranberryai/todak_todak_python/blob/master/machine_learning/regression/%E1%84%8B%E1%85%A1%E1%84%87%E1%85%A5%E1%84%8C%E1%85%B5%E1%84%8B%E1%85%A1%E1%84%83%E1%85%B3%E1%86%AF%E1%84%8F%E1%85%B5.xlsx?raw=true', sheet_name='train')
test_df = pd.read_excel('https://github.com/cranberryai/todak_todak_python/blob/master/machine_learning/regression/%E1%84%8B%E1%85%A1%E1%84%87%E1%85%A5%E1%84%8C%E1%85%B5%E1%84%8B%E1%85%A1%E1%84%83%E1%85%B3%E1%86%AF%E1%84%8F%E1%85%B5.xlsx?raw=true', sheet_name='test')

In [ ]:
pip install openpyxl

In [17]:
train_df.head()

Father      Son
0  165.100  151.892
1  165.100  160.782
2  167.132  159.512
3  155.194  163.322
4  160.020  163.068

In [18]:
test_df.head()

Father      Son
0  160.782  160.528
1  166.116  162.814
2  165.608  164.592
3  169.672  166.370
4  176.530  166.370

In [19]:
x_train = train_df.drop(['Son'], axis=1) # train_df['Father'] 도 가능 , 하지만 왼쪽 권장
x_test = test_df.drop(['Son'], axis=1)
y_train = train_df['Son']
y_test = test_df['Son']

x_train, y_train

(      Father
 0    165.100
 1    165.100
 2    167.132
 3    155.194
 4    160.020
 ..       ...
 750  186.182
 751  167.132
 752  181.102
 753  179.578
 754  178.562
 
 [755 rows x 1 columns],
 0      151.892
 1      160.782
 2      159.512
 3      163.322
 4      163.068
         ...   
 750    172.466
 751    154.940
 752    173.482
 753    176.022
 754    170.180
 Name: Son, Length: 755, dtype: float64)

In [20]:
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
x_train , x_test

(array([[165.1  ],
        [165.1  ],
        [167.132],
        [155.194],
        [160.02 ],
        [164.338],
        [167.894],
        [170.18 ],
        [149.86 ],
        [159.766],
        [161.798],
        [162.814],
        [164.338],
        [168.656],
        [166.624],
        [171.196],
        [172.212],
        [158.75 ],
        [162.052],
        [163.83 ],
        [165.1  ],
        [166.878],
        [166.37 ],
        [169.926],
        [169.164],
        [168.91 ],
        [173.482],
        [171.958],
        [173.99 ],
        [182.372],
        [163.83 ],
        [165.1  ],
        [166.878],
        [168.91 ],
        [164.846],
        [176.784],
        [164.592],
        [165.862],
        [166.624],
        [167.386],
        [167.132],
        [170.434],
        [169.164],
        [171.196],
        [170.942],
        [173.482],
        [172.974],
        [175.26 ],
        [175.006],
        [176.784],
        [178.816],
        [177.8  ],
        [184

In [21]:
model = LinearRegression()

In [22]:
model.fit(x_train, y_train)

LinearRegression()

In [23]:
# w 값 , b 값
model.coef_ , model.intercept_

(array([0.51820601]), 85.30837062148493)

In [24]:
##########모델 검증

# score : 회귀에서만 사용되는 R2제곱이라는 공식 , 1에 가까울 수록 좋음
# 1)
print(model.score(x_test, y_test))

0.2519977905846619


In [25]:
# 2) 오차 (mse or mae)
# y_train 값 - (x_train*model.coef_+model.intercept_)
# 각각 위 수식으로 작업하고 더한 뒤 평균을 냄

In [26]:
##########모델 예측
x_test = np.array([
    [164.338]
])

y_predict = model.predict(x_test)

print(y_predict)
print(y_predict[0]) #169.66660924268297

[170.46931036]
170.46931035654347


In [27]:
##########모델 예측

x_test = np.array([
    [164.338]
])

x_test = pd.DataFrame(x_test, columns=['Son'])

y_predict = model.predict(x_test)
print(y_predict)
print(y_predict[0]) #4.999995

[170.46931036]
170.46931035654347


c:\Users\user\miniconda3\envs\py\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [ ]:
# 토닥토닥 머신러닝