In [3]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('/content/drive/MyDrive/메타버스_아카데미_2기/딥러닝/7월/data/appreply.csv',index_col=0)
df.head(10)

text  score
0                                                NaN      4
1                                                NaN      5
2                                                NaN      1
3  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
4  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
5  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
6  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
7  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3
8  찜매장 구분 좀 해주세요! 대체 언제쯤이면 개선될까요?? 독점이라 해이한건가요? 유...      2
9  앱 실행시에 로그인 여부를 먼저 물어보고 비회원 이용을 선택할 경우, 혹은 나중에 ...      5

In [7]:
df = df.iloc[3:]
df

text  score
3     배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
4     내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
5     검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
6     배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
7     최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3
...                                                 ...    ...
998   갑자기 로그아웃 되더니 비밀번호 변경 실패 메세지가 계속 뜨네요. 휴대폰 번호로 인...      1
999   기사님이 상품 픽업을 하셨는지 표시되면 더 좋을 것 같습니다. 가게에서 조리가 늦게...      3
1000  요즘 요기요 보다 배민을 많이 쓰는 사람입니다 전화보다 앱을 써서 좀더 간편하고 다...      3
1001  취소 됐으면 적어도 전화 주는 제도는 있어야하는거 아닌가요? 주문해놓고 다른거 하는...      1
1002  배달의 민족 참 잘 사용하고 있어요. 별 다섯 개를 드리고 싶지만 한 가지 아쉬운 ...      4

[1000 rows x 2 columns]

In [8]:
df.reset_index(inplace=True)
df.head()

index                                               text  score
0      3  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
1      4  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
2      5  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
3      6  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
4      7  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3

In [9]:
df.drop(['index'],axis=1,inplace=True)
df.head()

text  score
0  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
1  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
2  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
3  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
4  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3

In [10]:
df = df.drop_duplicates(subset=['text'])
df

text  score
0    배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
1    내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
2    검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
3    배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
4    최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3
..                                                 ...    ...
995  갑자기 로그아웃 되더니 비밀번호 변경 실패 메세지가 계속 뜨네요. 휴대폰 번호로 인...      1
996  기사님이 상품 픽업을 하셨는지 표시되면 더 좋을 것 같습니다. 가게에서 조리가 늦게...      3
997  요즘 요기요 보다 배민을 많이 쓰는 사람입니다 전화보다 앱을 써서 좀더 간편하고 다...      3
998  취소 됐으면 적어도 전화 주는 제도는 있어야하는거 아닌가요? 주문해놓고 다른거 하는...      1
999  배달의 민족 참 잘 사용하고 있어요. 별 다섯 개를 드리고 싶지만 한 가지 아쉬운 ...      4

[1000 rows x 2 columns]

In [11]:
df.isnull().sum()

text     0
score    0
dtype: int64

In [12]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 82.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 56.1 MB/s eta 0:00:00


In [13]:
from konlpy.tag import Okt
from collections import Counter

In [14]:
text_data = ''.join(list(df['text']))
text_data

'배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,별점순 뿐만아니라 제가 주문하고자하는 메뉴를 특정해서 그 메뉴의 리뷰만 확인할 수 있는 기능이 있으면 좋을 것 같습니다. 메뉴검색 기능처럼 리뷰에서도 특정 메뉴 검색기능이 필요합니다. 주문수가 많지않은 메뉴의 리뷰를 보기 위해서 드래그하느라 시간이 많이 소요되는 비효율이 발생합니다. 긍정적으로 검토해주심 좋을 것 같습니다.내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 기억은 있는데 뭘시켰고 맛있게 먹은게 맞는지 알고싶은데 찾기가 너무 어렵네요.. 먹던 메뉴도 검색가능했으면 좋겠어요! 예를 들면 곱창 을 치면 과거에 시킨 곱창목록이 뜨거나 혹은 가게 리뷰창에 내리뷰보기 가 있어도 좋을거같아요 :)검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스크롤하는데 자꾸만 왼쪽 오른쪽으로 넘어가서 전체 탭이나 포장 탭을 보게 되는데 정말 불편합니다. 검색 후 배달 탭, 포장 탭, B마트 탭 뭐든 하나를 선택했으면 좌우로 넘기는 건 안 되게 하시면 안되나요? 가끔 그러는 것도 아니고 스크롤 한 번 내릴 때마다 왼쪽으로 넘어가서 전체 탭에 가게 되니까 너무 불편하고 답답해서 씁니다배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니다. 그리고 지역에 따라 추가 배달료가 있다고 별도로 체크하게 되어있어서 결국 배달팁은 5000원이 넘습니다. 10만원 이상 시키면 배달팁 0원이라는데 장난하는 것도 아니고.... 결국 하나하나 눌러가면서 가격대별 금액을 체크하고 배달팁 별도로 받는지도 확인해야합니다.최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 업데이트 하라고 나오고 업데이트 누르면 업데이트 진행은 안되고 열기 나오고 열기 누르면 업데이트 나오고 무한반복.. 수없이 삭제와 재설치 환경설정등을 해보아도 같은 증상이네요.. 다른분들도 다 같은 증상으로 보이는 글들을 보니

In [15]:
okt = Okt()
nouns = okt.nouns(text_data)
print(nouns)

['배달', '민족', '주문', '시', '리뷰', '자주', '참고', '편입', '니', '한가지', '건의', '사항', '최신', '순', '점순', '뿐', '제', '주문', '자하', '메뉴', '그', '메뉴', '리뷰', '확인', '수', '기능', '것', '메뉴', '검색', '기능', '리뷰', '특정', '메뉴', '검색', '기능', '주문', '수가', '메뉴', '리뷰', '보기', '위해', '드', '래그', '시간', '소요', '비', '효율', '발생', '긍정', '검토', '주심', '것', '내', '주문', '과거', '목록', '검색', '기능', '분명', '이', '가게', '기억', '뭘', '찾기', '메뉴', '검색', '예', '곱창', '치면', '과거', '곱창', '목록', '가게', '리뷰', '창', '리뷰', '보기', '검색', '화면', '전체', '배달', '포장', '탭', '중', '배달', '탭', '스', '크롤', '볼', '때', '아래', '스', '크롤', '자꾸만', '왼쪽', '오른쪽', '전체', '탭', '포장', '탭', '정말', '검색', '후', '배달', '탭', '포장', '탭', '마트', '탭', '뭐', '하나', '선택', '좌우', '건', '안', '가끔', '것', '스', '크롤', '번', '때', '왼쪽', '전체', '탭', '가게', '배달', '팁', '순', '정렬', '식', '가게', '가장', '위로', '지역', '추가', '배달', '료', '별도', '체크', '배달', '팁', '이상', '배달', '팁', '장난', '것', '하나', '하나', '가격', '대별', '금액', '체크', '배달', '팁', '별도', '확인', '최근', '업데이트', '안드로이드', '사양', '정도', '배민', '어플', '실행', '시', '업데이트', '하라', '업데이트', '업데이트', '진행', '열기', '열기',

In [16]:
#빈도수 체크
counter = Counter(nouns)
print(counter)

Counter({'배달': 939, '주문': 543, '가게': 373, '리뷰': 352, '앱': 349, '메뉴': 341, '배민': 300, '수': 288, '사용': 282, '것': 257, '결제': 242, '기능': 234, '때': 226, '어플': 223, '검색': 197, '음식': 193, '업데이트': 178, '쿠폰': 176, '더': 173, '다시': 168, '시간': 159, '취소': 156, '좀': 140, '점': 140, '확인': 139, '왜': 138, '비': 130, '고객': 127, '화면': 126, '전화': 125, '개선': 121, '로그인': 115, '다른': 114, '계속': 113, '안': 111, '이용': 109, '거': 109, '추가': 108, '문제': 103, '이': 102, '생각': 102, '선택': 101, '그': 96, '번': 95, '사람': 94, '제': 93, '팁': 92, '경우': 91, '곳': 91, '진짜': 90, '오류': 89, '후': 88, '정말': 85, '요': 85, '찜': 84, '그냥': 84, '설정': 83, '하나': 82, '삭제': 78, '매장': 78, '민족': 77, '사항': 76, '뭐': 76, '볼': 74, '순': 73, '요청': 73, '개': 73, '내': 72, '이벤트': 72, '시': 71, '기사': 71, '저': 70, '인증': 70, '별로': 69, '바로': 69, '전': 69, '사진': 68, '입력': 66, '시스템': 66, '포장': 64, '서비스': 64, '말': 64, '음식점': 63, '업체': 63, '목록': 62, '한번': 62, '때문': 62, '할인': 61, '카드': 61, '센터': 60, '주소': 59, '자주': 58, '또': 58, '연결': 58, '부분': 57, '집': 57, '등록': 57, '금액

In [17]:
noun_data = Counter({x:counter[x] for x in counter if len(x) > 1})
noun_data.most_common(10)

[('배달', 939),
 ('주문', 543),
 ('가게', 373),
 ('리뷰', 352),
 ('메뉴', 341),
 ('배민', 300),
 ('사용', 282),
 ('결제', 242),
 ('기능', 234),
 ('어플', 223)]

In [1]:
import re
from tqdm import tqdm

noun_result = []  #[ [] , [], [] ]

for temp in tqdm(df['text']):
    han = re.compile('[^ㄱ-ㅣ가-힣]')
    temp_result = han.sub(' ',temp) #문장에서 한글만 남기고 제거
    temp_noun = okt.nouns(temp_result)
    result_noun = [ x for x in temp_noun if len(x) >1]
    noun_result.append(result_noun)

print(noun_result)

NameError: ignored

In [19]:
# bag of word 벡터 생성
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(tokenizer=lambda x:x,lowercase=False)
bow_vect = count_vectorizer.fit_transform(noun_result)
word_list = count_vectorizer.get_feature_names_out()
print(word_list)
print(len(word_list))

['가게' '가격' '가계' ... '희망' '흰색' '히어로']
2795


/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [20]:
bow_vect.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
len(bow_vect.toarray()[0])

2795

In [23]:
from pandas.core.generic import Axis
# 단어별 전체 등장 횟수
count_list = bow_vect.toarray().sum(axis=0)
# 가게 373번 등장, 가격 41번등장
count_list

array([373,  41,   1, ...,   1,   1,   1])

In [24]:
word_count = dict(zip(word_list,count_list))
word_count

{'가게': 373,
 '가격': 41,
 '가계': 1,
 '가공': 2,
 '가관': 2,
 '가구': 1,
 '가기': 10,
 '가까스로': 1,
 '가까윤': 1,
 '가까이': 2,
 '가끔': 20,
 '가나': 3,
 '가능': 17,
 '가도': 2,
 '가독성': 1,
 '가뜩이나': 2,
 '가라': 2,
 '가량': 2,
 '가령': 1,
 '가로': 1,
 '가르침': 1,
 '가맹': 7,
 '가면': 6,
 '가방': 2,
 '가성': 2,
 '가안': 1,
 '가야': 4,
 '가요': 31,
 '가운데': 1,
 '가원': 3,
 '가이드': 2,
 '가입': 54,
 '가입자': 1,
 '가장': 19,
 '가정': 3,
 '가족': 8,
 '가족사진': 1,
 '가지': 36,
 '가짐': 1,
 '가짜': 1,
 '가치': 2,
 '각고': 1,
 '각성': 1,
 '각오': 1,
 '각종': 2,
 '간다': 1,
 '간만': 1,
 '간반': 1,
 '간좀': 1,
 '간지': 1,
 '간짜장': 1,
 '간편': 4,
 '간혹': 4,
 '갈리': 1,
 '갈수': 2,
 '갈수록': 15,
 '감고': 1,
 '감당': 1,
 '감사': 7,
 '감성': 1,
 '감소': 1,
 '감수': 1,
 '감안': 2,
 '감자': 2,
 '감정': 4,
 '갑니닼': 1,
 '갑자기': 30,
 '강국': 1,
 '강요': 4,
 '강원도': 1,
 '강의': 1,
 '강점': 1,
 '강제': 11,
 '강조': 3,
 '강탈': 2,
 '개념': 2,
 '개도': 5,
 '개돼지': 1,
 '개발': 16,
 '개발자': 19,
 '개별': 5,
 '개보': 1,
 '개불': 1,
 '개뿔': 2,
 '개선': 121,
 '개속': 1,
 '개수': 5,
 '개승': 1,
 '개악': 1,
 '개열': 1,
 '개월': 4,
 '개인': 18,
 '개인정보': 3,
 '개인정보보호법': 1,
 '개판': 2,
 '개편'

In [26]:
# if-idf 생성
from sklearn.feature_extraction.text import TfidfTransformer

tf_vectorizer = TfidfTransformer()
# bow vector를 tf_vectorizer에 넣으면 됌
tf_idf = tf_vectorizer.fit_transform(bow_vect)
# 단어의 가중치가 계산됌
tf_idf.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.19910076, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.07763765, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06731077, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [29]:
# 4점 부터 긍정 or 그 이하는 부정
df.head()

text  score
0  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4
1  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5
2  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1
3  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2
4  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3

In [30]:
df['score_real'] = np.where(df['score']>= 4,1,0)
df.head(5)

text  score  score_real
0  배달의민족 주문시 리뷰를 자주 참고하는 편입니다. 한가지 건의사항이 있다면 최신순,...      4           1
1  내가 주문했던 과거목록에서도 검색기능이 있었으면 좋겠어요.. 분명 이 가게에 시킨 ...      5           1
2  검색 화면에서 전체/배달/포장 탭 중 배달 탭을 스크롤 내리면서 볼 때, 아래로 스...      1           0
3  배달팁 낮은 순으로 정렬하면 0~4000원 이런식으로 된 가게가 가장 위로 올라옵니...      2           0
4  최근 업데이트가 안드로이드5사양 정도에서는 안되는것 같습니다.. 배민 어플 실행시 ...      3           0

In [31]:
df['score_real'].value_counts()

0    729
1    271
Name: score_real, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split

x = tf_idf
y = df['score_real']

# 데이터 불균형 => stratify
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=1,stratify=df['score_real'])

In [33]:
X_train.shape , X_test.shape

((700, 2795), (300, 2795))

In [34]:
# 모델 학습 (이진 분류)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

lr_model = LogisticRegression(random_state=1)
lr_model.fit(X_train,y_train)

LogisticRegression(random_state=1)

In [35]:
y_pred = lr_model.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [36]:
accuracy_score(y_test,y_pred)

0.7933333333333333

In [37]:
precision_score(y_test,y_pred)

0.88

In [39]:
# 긍정 or 부정으로 분류되는데 큰 영향을 미치는 단어들
invert_index_vectorizer = {v:k for k,v in count_vectorizer.vocabulary_.items()}
invert_index_vectorizer

{969: '배달',
 907: '민족',
 2181: '주문',
 718: '리뷰',
 1974: '자주',
 2311: '참고',
 2551: '편입',
 2643: '한가지',
 130: '건의',
 1194: '사항',
 2375: '최신',
 2079: '점순',
 1978: '자하',
 807: '메뉴',
 2747: '확인',
 321: '기능',
 131: '검색',
 2517: '특정',
 1318: '수가',
 1030: '보기',
 1794: '위해',
 680: '래그',
 1386: '시간',
 1302: '소요',
 2776: '효율',
 945: '발생',
 316: '긍정',
 137: '검토',
 2191: '주심',
 218: '과거',
 845: '목록',
 1088: '분명',
 0: '가게',
 341: '기억',
 2319: '찾기',
 203: '곱창',
 2409: '치면',
 2740: '화면',
 2060: '전체',
 2569: '포장',
 2459: '크롤',
 1472: '아래',
 1958: '자꾸만',
 1720: '왼쪽',
 1681: '오른쪽',
 2099: '정말',
 749: '마트',
 2621: '하나',
 1259: '선택',
 2169: '좌우',
 10: '가끔',
 2096: '정렬',
 33: '가장',
 1788: '위로',
 2246: '지역',
 2382: '추가',
 1022: '별도',
 2349: '체크',
 763: '만원',
 1862: '이상',
 1994: '장난',
 1: '가격',
 542: '대별',
 312: '금액',
 2368: '최근',
 1601: '업데이트',
 1502: '안드로이드',
 1176: '사양',
 2094: '정도',
 972: '배민',
 1583: '어플',
 1446: '실행',
 2629: '하라',
 2279: '진행',
 1656: '열기',
 865: '무한',
 938: '반복',
 1196: '삭제',
 1267: '설치

In [47]:
coef_pos_index = sorted(((v,idx) for idx,v in enumerate(lr_model.coef_[0])),reverse=True)
coef_pos_index

[(2.1016043607710055, 807),
 (1.9760471135119515, 321),
 (1.9297588938631116, 1179),
 (1.82115070681151, 718),
 (1.2889263573014347, 1194),
 (1.2689054870540104, 471),
 (1.222024384620986, 2425),
 (1.206657976042732, 1532),
 (1.1296264693275129, 1259),
 (1.0290021412807886, 1168),
 (1.0093277234918945, 2382),
 (0.9991892384537089, 2643),
 (0.9721510182420862, 1818),
 (0.9478125222001078, 130),
 (0.8122602839302695, 922),
 (0.805871930187918, 812),
 (0.7628438575582399, 0),
 (0.7548557469700542, 1702),
 (0.7389823541534641, 1646),
 (0.6661481136420254, 2583),
 (0.6651119587722298, 749),
 (0.6620889242340136, 2729),
 (0.6509412255474898, 1998),
 (0.6412612850975848, 1707),
 (0.6390953853622041, 2099),
 (0.634387915418967, 1017),
 (0.6277822413548682, 131),
 (0.6267524280050302, 2161),
 (0.6198537471124624, 1974),
 (0.6148435169025451, 1211),
 (0.6127187300262956, 84),
 (0.6121900120438807, 2599),
 (0.6115557430925755, 1087),
 (0.6013966344578936, 2447),
 (0.5885186621227916, 1237),
 (0.5

In [48]:
for coef in coef_pos_index[:20] :
    print(invert_index_vectorizer[coef[1]], coef[0])

메뉴 2.1016043607710055
기능 1.9760471135119515
사용 1.9297588938631116
리뷰 1.82115070681151
사항 1.2889263573014347
다만 1.2689054870540104
카테고리 1.222024384620986
애용 1.206657976042732
선택 1.1296264693275129
사람 1.0290021412807886
추가 1.0093277234918945
한가지 0.9991892384537089
음식 0.9721510182420862
건의 0.9478125222001078
바로 0.8122602839302695
메모 0.805871930187918
가게 0.7628438575582399
옵션 0.7548557469700542
역시 0.7389823541534641
표시 0.6661481136420254


In [58]:
def comment_predict(text):
  sentence_test = text
  # han = re.compile('[^ㄱ- | 가-힣]')
  han = re.compile('[^ㄱ-ㅣ 가-힣]')
  temp_result = han.sub(' ',sentence_test)
  temp_noun = okt.nouns(temp_result)
  result_noun = [x for x in temp_noun if len(x)>1]

  # transform만 (fit하면 안됌)
  vec_test = count_vectorizer.transform([result_noun])
  vec_test.toarray().sum()
  tf_test = tf_vectorizer.transform(vec_test)
  tf_test.toarray().sum()

  result = ''
  if lr_model.predict(tf_test) == 1:
    result = '긍정'
  else:
    result = '부정'

  return result

print(comment_predict('메뉴가 다양해서 좋았어요'))

긍정


In [59]:
print(comment_predict('서비스가 엉망이에요'))

부정
