# 함수

In [ ]:
# https://wikidocs.net/24

In [1]:
def add_many(*args): 
    result = 0 
    for i in args: 
        result = result + i 
    return result 

In [2]:
add_many(1,2,3,4,5)

15

In [3]:
# *매개변수

def add_mul(choice, *args): 
    if choice == "add": 
        result = 0 
        for i in args: 
            result = result + i 
    elif choice == "mul": 
        result = 1 
        for i in args: 
            result = result * i 
    return result 

In [4]:
add_mul('add',1,2,3,4,5)

15

In [5]:
# 키워드 매개변수

def kwargs_test(**kwagrs):
    print(kwagrs)
kwargs_test(a=1)

{'a': 1}


In [6]:
# 초기값

def say_myself(name, age, man=True): 
    print("나의 이름은 %s 입니다." % name) 
    print("나이는 %d살입니다." % age) 
    if man: 
        print("남자입니다.")
    else: 
        print("여자입니다.")

In [7]:
say_myself('임정민',27)

나의 이름은 임정민 입니다.
나이는 27살입니다.
남자입니다.


In [8]:
say_myself('임정민',27,True)

나의 이름은 임정민 입니다.
나이는 27살입니다.
남자입니다.


In [9]:
# lambda 식
add = lambda a, b: a+b
result = add(3, 4)
print(result)

7


In [10]:
mul = lambda a,b : a*b
mul(1,2)

2

In [12]:
t1 = '정민'
t2 = '민정'
print(t1,t2)
print(t1,t2,sep='') # 매개변수 초기화

정민 민정
정민민정


In [13]:
print(t1,t2,sep=',',end='----') # 매개변수 초기화
print(t1,t2,sep=',') # 매개변수 초기화

정민,민정----정민,민정


In [14]:
zip([1, 2, 3], [4, 5, 6])

In [15]:
list(zip([1, 2, 3], [4, 5, 6]))

[(1, 4), (2, 5), (3, 6)]

In [16]:
dict1 = { 'name' : ['bu','gi','on'],
         'phone' : ['010','011','013'],
         'birth' : ['0516','0101','0731']
         }
dict1.keys()

dict_keys(['name', 'phone', 'birth'])

In [17]:
dict1.values()

dict_values([['bu', 'gi', 'on'], ['010', '011', '013'], ['0516', '0101', '0731']])

In [19]:
# json 
dict2 = { 'info' : { 
                    'le' : 'python',
                    'wr' : 'bu',
                    'date' : '2023',
                    'ver' : '1.0'
                    }
                    ,

         'data' : {
                    'name' : ['bu','gi','on'],
                    'phone' : ['010','011','013'],
                    'birth' : ['0516','0101','0731'],
                    'eye' : {
                            'eyeL' : [1.0,2.0,1.5],
                            'eyeR' : [1.5,1.2,2.0]
                            }
                    }
        }

dict2['data']['name']

['bu', 'gi', 'on']

In [20]:
dict2['data']['eye']['eyeR']

[1.5, 1.2, 2.0]

In [22]:
import numpy as np
import pandas as pd
data = np.random.rand(5,3)*7
data = data.astype('int32')
data

array([[0, 4, 6],
       [5, 6, 3],
       [0, 2, 5],
       [2, 2, 6],
       [1, 4, 0]])

In [23]:
df = pd.DataFrame(data,columns=['kor','eng','mat'])
df

kor  eng  mat
0    0    4    6
1    5    6    3
2    0    2    5
3    2    2    6
4    1    4    0

In [24]:
dict3 = {'kor':[9,5,3],'eng':[2,3,4],'mat':[3,7,3]}
pd.DataFrame(dict3)

kor  eng  mat
0    9    2    3
1    5    3    7
2    3    4    3

In [25]:
# 크롤링 후 Dataframe으로 저장할 시
# 다음과 같이 저장함

# for 크롤링:
    # korList.append()
# dict3 = {'kor': korList,'eng':[2,3,4],'mat':[3,7,3]}
# pd.DataFrame(dict3)

In [37]:
# 임의의 가중치

w = np.random.rand(3)*7
w = w.astype('int32')
w

array([4, 5, 3])

In [38]:
df.values

array([[0, 4, 6],
       [5, 6, 3],
       [0, 2, 5],
       [2, 2, 6],
       [1, 4, 0]])

In [39]:
df.values * w

array([[ 0, 20, 18],
       [20, 30,  9],
       [ 0, 10, 15],
       [ 8, 10, 18],
       [ 4, 20,  0]])

In [40]:
# 예측값 계산

np.dot(df.values,w)

array([38, 59, 25, 36, 24])

In [42]:
def makeW(len_df_colums):

    w = np.random.rand(len_df_colums)*10
    w = w.astype('int32')

    return w

def cal(data,w):
    
    return np.dot(data,w)

w = makeW(len(df.columns))

cal(df,w)

array([72, 90, 52, 72, 30])